source 'https://github.com/CocoaPods/Specs.git'

target 'RMImageCropper', :exclusive => true do
  pod "RMImageCropper", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "RMImageCropper", :path => "../"

  
end
